services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - ./app:/app
    command: make dev

  caddy:
    image: caddy:2.8-alpine
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
